frontend/
├── public/                      # Static files (publicly accessible)
│   ├── favicon.ico              # Favicon for your website
│   └── (other static assets)
├── src/
│   ├── app/
│   │   ├── layout.tsx           # Root layout
│   │   ├── page.tsx             # Home/Index page
│   │   ├── login/
│   │   │   └── page.tsx         # Login page
│   │   ├── dashboard/
│   │   │   └── page.tsx         # Dashboard page
│   ├── components/              # Reusable components
│   │   ├── Navbar.tsx
│   │   └── (other components...)
│   ├── styles/                  # Global styles and Tailwind configuration
│   │   ├── globals.css          # Global CSS styles (imported in layout.tsx)
│   └── utils/                   # Utility functions and hooks
│       └── (utility files...)
├── .env.local                   # Environment variables (for local development)
├── Dockerfile                   # Dockerfile for frontend
├── next-env.d.ts                # TypeScript types for Next.js (auto-generated)
├── next.config.mjs              # Next.js configuration file (ESM format)
├── node_modules/                # Installed dependencies (auto-generated by npm)
├── package-lock.json            # Lock file for installed dependencies (auto-generated)
├── package.json                 # Dependencies and scripts for the project
├── postcss.config.mjs           # PostCSS configuration (used by Tailwind CSS)
├── tailwind.config.ts           # Tailwind CSS configuration file
└── tsconfig.json                # TypeScript configuration file
