name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build

    - name: Build Docker image
      run: docker build -t frontend-app .

    - name: Push Docker image to registry
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/yourusername/frontend-app:latest

    - name: Deploy (optional, if you have a deployment step)
      run: |
        # Add your deployment script here
        echo "Deploying the frontend app..."
